image: php:8.0-cli

before_script:
  - apt-get update
  - apt-get install -y git libxml2-dev zlib1g-dev
  - docker-php-ext-install zip > /dev/null
  - curl -s https://raw.githubusercontent.com/composer/getcomposer.org/master/web/installer | php -- --quiet --install-dir="/usr/local/bin" --filename="composer"

deploy-ter:
  tags:
    - docker
  only:
    - tags
  script:
    - |
      if [ -n "$TYPO3_API_USERNAME" ] && [ -n "$TYPO3_API_PASSWORD" ]; then
        echo "Releasing ${CI_COMMIT_TAG} to ter.typo3.org"
        composer global require typo3/tailor
        # Create a new api token that exipres after 10 minutes (minimum time is 60 seconds)
        TYPO3_API_TOKEN=$($HOME/.composer/vendor/bin/tailor ter:token:create --name="token for nws_municipal_statutes $CI_COMMIT_TAG publishing" --extensions=nws_municipal_statutes --raw --expires=600 | jq -r ".access_token")
        # cleanup before upload
        rm -rf build vendor .git* composer.lock gulpfile.js package.json Resources/Private/Sources .jshintrc
        $HOME/.composer/vendor/bin/tailor ter:publish "$CI_COMMIT_TAG" nws_municipal_statutes
      fi;
